// Mocks generated by Mockito 5.4.0 from annotations
// in yummy/test/features/colors/domain/usecases/get_all_color_sets_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:yummy/core/error/failure.dart' as _i5;
import 'package:yummy/features/app_colors/data/models/colors_model.dart' as _i7;
import 'package:yummy/features/app_colors/domain/entities/colors_entity.dart'
    as _i6;
import 'package:yummy/features/app_colors/domain/repository/colors_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ColorsRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockColorsRepository extends _i1.Mock implements _i3.ColorsRepository {
  @override
  _i4.Future<
      _i2
          .Either<_i5.Failure, List<_i6.ColorsEntity>>> getAllColorSets() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllColorSets,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ColorsEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ColorsEntity>>(
          this,
          Invocation.method(
            #getAllColorSets,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, List<_i6.ColorsEntity>>>.value(
                _FakeEither_0<_i5.Failure, List<_i6.ColorsEntity>>(
          this,
          Invocation.method(
            #getAllColorSets,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, List<_i6.ColorsEntity>>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> saveColorSet(
          _i7.ColorsModel? entity) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveColorSet,
          [entity],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveColorSet,
            [entity],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #saveColorSet,
            [entity],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> removeColorSet(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeColorSet,
          [id],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
            _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeColorSet,
            [id],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Failure, void>>.value(
                _FakeEither_0<_i5.Failure, void>(
          this,
          Invocation.method(
            #removeColorSet,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
